# Pipeline to build and publish for deployment

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  fastSolution: '**/Net50WindowsDeploymentTest.sln'
  publishProjects: '**/Net50WindowsDeploymentTest.csproj'
  buildConfiguration: 'Release'

steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: $(fastSolution)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(fastSolution)
    publishWebProjects: false
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    projects: $(publishProjects)
    arguments: '--configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory) --self-contained true --runtime win-x86 --no-build'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'