# Pipeline to build and publish for deployment

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  fastSolution: '**/Fast.sln'
  buildConfiguration: 'Release'

steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: $(fastSolution)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --self-contained true'
