# Pipeline to build and publish for deployment

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  fastSolution: '**/Net50WindowsDeploymentTest.sln'
  publishProjects: '**/Net50WindowsDeploymentTest.csproj'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(fastSolution)
    feedsToUse: 'select'
    vstsFeed: 'd589caf8-6e77-4aa6-9ffd-e644da7de4b1/f566eb63-1603-4f24-bf96-70495e7e38e7'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(fastSolution)
    publishWebProjects: false
    arguments: '--configuration $(buildConfiguration) --runtime win-x64 --no-restore'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    projects: $(publishProjects)
    arguments: '--configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory) --self-contained true --runtime win-x64 --no-build'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'